
import Logo from '@/icons/logo.svg';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Test compiler swc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img.jpg" />
      </Head>
      <main style={{ backgroundColor: 'blueviolet', padding: '30px' }}>
        <h1>Test compiler SWC!</h1>
        <Logo />
      </main>
    </>
  );
}
